### ISSUE TITLE
AIF drops all traffic on force-reload

### ISSUE THREAD

**Issue by arnova** [arno-iptables-firewall/aif#1]
Due to the implementation of our current blocked-hosts batch loader, we drop all firewall traffic on force-reload because we temporarely set the fw policy to drop while reloading. Especially with large lists of blocked hosts this is undesireable. Perhaps we should fix this by using a passive and an active chain?

**Comment by abelbeck** [comment]
@arnova I'm in the process of adding optional ```ipset``` support when ```IPTABLES_IPSET=1``` is defined.

Not only is this much faster, but 'sets' can be swapped, so during force-reload the old set can be still active while the new set is being created, then swapped and the old set destroyed.  No need to drop new traffic during force-reload.

Works quite nicely in my testing, down the road we can make this the default but we need more testing.

**Comment by abelbeck** [comment]
Fixed in 2.0.1g with IPTABLES_IPSET=1
