### ISSUE TITLE
unable to perform unattended install on Ubuntu

### ISSUE THREAD

**Issue by P0lymorph** [arno-iptables-firewall/aif#14]
I am trying to perform an unattended install (i.e. without user interaction) of arno-iptables-firewall.
I have setup predefined answers using debconf-set-selections before running the apt-get install -q -y arno-iptables-firewall but the debconf answer are ignored.
Is it on purpose? what is the supported way to perform unattended setup on Ubuntu?

**Comment by arnova** [comment]
Rather old issue but debconf related things should go to Debian's bugtracker, there isn't much we can do about it. If still an issue, file a bug report there.
