### ISSUE TITLE
Error: /usr/sbin/iptables: (4) Another app is currently holding the xtables lock.

### ISSUE THREAD

**Issue by abelbeck** [arno-iptables-firewall/aif#17]
In AstLinux we recently updated iptables to version 1.4.21, and very rarely, usually a background plugin can generate either error below:
```
/usr/sbin/iptables: (4) Another app is currently holding the xtables lock.
Perhaps you want to use the -w option?
```
or
```
/usr/sbin/ip6tables: (4) Another app is currently holding the xtables lock.
Perhaps you want to use the -w option?
```

Digging deeper, this change occurred with iptables 1.4.20, from Changelog...
ip[6]tables: Add locking to prevent concurrent instances

Discussion and preliminary patch:
http://patchwork.ozlabs.org/patch/246619/

In my limited testing, I can forcibly generate the error, and adding -w seems to gracefully work.

We need to automatically handle this in AIF since it could mean a rule does not get applied while the firewall is being built.

Fortunately, adding a -w is only needed in 4 lines in environment.

grep 'IP[46]TABLES ' /usr/share/arno-iptables-firewall/environment
```
  result=`$IP4TABLES "$@" 2>&1`
  result=`$IP6TABLES "$@" 2>&1`
  $IP4TABLES "$@" >/dev/null 2>&1
  $IP6TABLES "$@" >/dev/null 2>&1
```
Checking for iptables-1.4.20+ is probably the most work :-)

And *much* testing...

**Comment by arnova** [comment]
Perhaps first push a new stable release before we implement this? Any other issues that need resolving before we do this?

**Comment by abelbeck** [comment]
Per my testing, I think it is important the next release addresses this issue, and the fix I committed seems to work nicely.  On an Intel Atom box manually running 'arno-iptables-firewall status-plugins' multiple times while 'arno-iptables-firewall restart' is executing easily drops rules and generates the error described above without the fix.

Note that Debian jessie includes iptables 1.4.21
https://packages.debian.org/hu/jessie/iptables

Yes, we are due a new release, perhaps a RC1 for a few weeks before releasing the final version.

Related, your new additions to tracking plugin errors, that seems optional to existing custom plugins correct ?  This does not require any tweaks to pre-existing plugins unless they wanted errors to percolate to the top, correct ?

**Comment by arnova** [comment]
Hmmm, how unfortunate it is then that we were unable to detect this issue before Jessie was released. But agreed, let's get this in and package an RC and see how it goes.

Yes, the plugin error tracking is completely optional and backwards compatible. Note that e.g. the PLUGIN_RETVAL was always there but never used. I probably simply forgot back then (can't recall must be getting old ;-)). Most important change is the explicit detection of iptables errors that occurred during the load of a plugin which obviously always works as it's handled in the main script.

**Comment by abelbeck** [comment]
The iptables folks had a tough decision to make whether the -w option was enabled by default or not, they chose not.  The result is in the past very rarely generating "iptables: Resource temporarily unavailable", you can now generate "Another app is currently holding the xtables lock" very easily.  The good news is adding -w now does the right thing and makes iptables more robust.

As I mentioned the fix has been added to master, referenced above "Enable xtables lock..."

**Comment by arnova** [comment]
I'm wondering what stuff is running in the background that uses iptables? Fail2ban ?

**Comment by abelbeck** [comment]
Possibly Fail2ban, or any of our plugins that have a background script, or processes that can call iptables like miniupnpd.  If it can happen, it will happen when you don't want it to happen. :-)

**Comment by abelbeck** [comment]
Are we ready for RC1 ?
