### ISSUE TITLE
No default install

### ISSUE THREAD

**Issue by nemysis** [arno-iptables-firewall/aif#18]
I try to make openSUSE RPM for Arno's iptables firewall script

But get than nemysis user for openSUSE Build Service can't make RPM. Tthat works only that root. This is not usual.

Please make one Makefile for installation and configure when needed.

**Comment by arnova** [comment]
This is not an AIF problem per se. Instead of a Makefile we use an install script. Automatically creating RPMs doesn't work this so someone with proper knowledge should create an actual RPM manually.
