### ISSUE TITLE
Rare: Invalid conntrack state when AIF first starts

### ISSUE THREAD

**Issue by abelbeck** [arno-iptables-firewall/aif#19]
For many years I have had an annoying, but hard to reproduce issue with a SIP ATA (Analog Terminal Adapter) behind NAT.

The ATA is a Grandstream (not my choice) specifically configured for my home alarm system for remote monitoring.  The alarm provider automatically provisions it.

The problem is the ATA looses it's register when AstLinux using AIF reboots, but only 1 (or 2) out of 10 times.  This has been an issue for many years, various AIF versions and iptables versions.

The problem seems to be an outbound UDP packet is generated by the ATA before the firewall is completely built, causing a stuck inappropriate conntrack state.

Normally the connection state should look like this with a 3:00 TTL
```
10.10.22.40  5060  184.73.xxx.xxx  5060  UDP  2:47
```

When it fails the state only has a 1:00 TTL
```
10.10.22.40  5060  184.73.xxx.xxx  5060  UDP  0:57
```

My hunch is this occurs when the UDP packet is allowed into the INPUT chain but before the NAT POSTROUTING rules are applied.

With the incorrect state, fixing it is a pain, either unplugging the ATA for 1 minute, (wait for the conntrack state to expire) or playing iptables games to block 10.10.22.40 UDP, reboot the ATA, wait 1 minute, then allow 10.10.22.40 UDP in.

I suspect this issue is only noticed for devices that force a fixed source and destination port so any retries always hits the same conntrack state.

Anyone see this ?

**Comment by abelbeck** [comment]
I tried the following patch to more precisely block input/forward packets while the firewall is being populated...
```
--- /usr/sbin/arno-iptables-firewall
+++ /usr/sbin/arno-iptables-firewall
@@ -861,10 +861,11 @@
     echo "IPv4 mode selected, no IPv6 available"
   fi
 
-  # The POST_INPUT_DROP_CHAIN should temporarily DROP for now
+  # The Base INPUT/FORWARD chains should temporarily default to DROP
   # We'll change this once the rules are in place
   ###########################################################
-  iptables -A POST_INPUT_DROP_CHAIN -j DROP
+  iptables -A BASE_INPUT_CHAIN -j DROP
+  iptables -A BASE_FORWARD_CHAIN -j DROP
 
   # The HOST_BLOCK_DROP chain should always DROP
   ###########################################################
@@ -4647,9 +4648,6 @@
   # Drop all packets at the end of the POST_INPUT_DROP_CHAIN
   iptables -A POST_INPUT_DROP_CHAIN -j DROP
 
-  # Remove the temp rule at the beginning of the POST_INPUT_DROP_CHAIN
-  iptables -D POST_INPUT_DROP_CHAIN 1
-
   ###############################################################################################
   # FORWARD rules                                                                               #
   ###############################################################################################
@@ -4992,6 +4990,10 @@
   # Clean-up DNS output rules
   iptables -D OUTPUT_CHAIN 2
   iptables -D OUTPUT_CHAIN 1
+
+  # Remove default DROP rule for the Base INPUT/FORWARD chains
+  iptables -D BASE_INPUT_CHAIN -j DROP
+  iptables -D BASE_FORWARD_CHAIN -j DROP
 }
 
 
```
While the above change may be a good addition, it did not solve my ATA issue.

I'm starting to think the issue is ATA firmware related or Alarm provider related.

**Comment by abelbeck** [comment]
It seems I found a solution, and brain damaged ATA firmware (or configuration) appears to be the source of the problem.

Using the AIF custom rule:
```
start_port=$(((RANDOM%100)+5100))
end_port=$((start_port+10))

echo "[CUSTOM RULE] Rewrite outbound 10.10.22.40 SIP source port from 5060 to $start_port"
ip4tables -t nat -A POSTROUTING -o eth0 -p udp --sport 5060 --dport 5060 -s 10.10.22.40 -j MASQUERADE \
         --to-ports ${start_port}-${end_port}

start_port=$((end_port+1))
end_port=$((start_port+10))

ip4tables -t nat -A POSTROUTING -o eth0 -p udp --sport 5060 --dport 514 -s 10.10.22.40 -j MASQUERADE \
         --to-ports ${start_port}-${end_port}

unset start_port end_port
```
The port randomization should help with any remote stale firewall states, and separating the SIP (UDP 5060) and syslog (UDP 514) connections to different port ranges seems to fix the problem.

The Grandstream ATA has a "Use Random Port" setting, but the auto-provision set's it to NO .

Additionally, why the ATA's syslog connection should also have a source port of 5060 seems like a bug.

**Comment by arnova** [comment]
This is pretty lame yes, always nice having to work around manufacturer bugs. Sounds a little bit like the hacks I had to apply in "the beginning" to have NFS work properly during bootup.
