### ISSUE TITLE
better with ipset

### ISSUE THREAD

**Issue by cybernard** [arno-iptables-firewall/aif#24]
this program is in need of ipset intervention in addition to iptables.  Loading and saving times will be dramatically faster as you can load and save all sets with 1 command.  ipset save -f  something.txt
ipset restore -f something.txt

You could probably eliminate some the for next loops.  Also the way your doing things a list of 20000 ip's, which I have 88000+ would cause the CPU to run at 100% and be slow.  You add 1 iptables rule for every IP and with ipset you only need 1 iptables entry for any number of ip's.

ipset -! -N ban_ip hash:net counters
iptables -A INPUT -m set --set ban_ip src -j DROP
OR
ipset -N ban_ip hash:net counters timeout 300 comment
300 is just the default

ipset add ban_ip 1.1.1.1  adds to the list
OR
ipset add ban_ip 1.1.1.1 timeout 60
OR 
ipset add ban_ip 1.1.1.1 timeout 60 comment "evil doers r us"

iptables -A ban_ip -j SET  --add-set banned_hosts src

**Comment by abelbeck** [comment]
I think even today we can't assume ipset is available (requires kernel 3.x and the ipset package) , so we would need to come up with a method to do certain things two different ways.

Something to think about though.

**Comment by cybernard** [comment]
Clearly, if you still have a kernel that doesn't support it, keep doing things the old way.  For the rest of people who have come into the modern era ipset is the way to go, and tell people in a log message that they should upgrade their kernels.  Many people don't know any better. 

The different is orders of magnitude, and my ban list is 130,000+, which would bring the CPU running your system to its knees.

**Comment by cybernard** [comment]
Here is a rules set for systemd if you need one


save as /usr/lib/systemd/system/ipset.service
systemctl enable ipset
---------------------------------------
[Unit]
Description=IP sets for iptables
After=ufw.service
Before=network.target
Before=iptables.service
Before=webmin-iptables.service
AssertPathExists=/src/all.txt

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=-/bin/echo 'Loading ipset sets'
ExecStart=/sbin/ipset restore -f /src/all.txt
ExecStop=/sbin/ipset save -f /src/all.txt
ExecStartPost=-/bin/echo 'Saving ipsets to disk'
#ExecReload=/usr/libexec/ipset/ipset.start-stop reload
# Save current ipset entries on stop/restart.
#   Value: yes|no,  default: no
# Saves all ipsets to /etc/sysconfig/ipset if ipset gets stopped
Environment=IPSET_SAVE_ON_STOP=yes IPSET_SAVE_ON_RESTART=no
ReadWriteDirectories=/src
NoNewPrivileges=yes

[Install]
WantedBy=basic.target

**Comment by abelbeck** [comment]
Fixed in 2.0.1g
