### ISSUE TITLE
Problem with ICMP request

### ISSUE THREAD

**Issue by StephaneMangin** [arno-iptables-firewall/aif#25]
Hi,

It's issue is probably due to my fault but, i suppose that my configuration is right.
ICMP requests does not work at all.

Here is my configuration file in case of mistake : 

    EXT_IF="eth0"
    EXT_IF_DHCP_IP=0
    INT_IF="lxcbr0"
    INTERNAL_NET="172.4.1.0/24"
    OPEN_ICMP=1
    ECHO_IGNORE=0
    ICMP_REDIRECT=1
    OPEN_TCP="80, 443, 587, 143, 5000, 22, 9001"
    OPEN_UDP="80, 443, 587, 143, 5000, 22, 9001"
    NAT=1
    NAT_INTERNAL_NET="172.24.1.0/24"
    NAT_TCP_FORWARD="143,587>172.24.1.3 80,443>172.24.1.2"
    NAT_UDP_FORWARD="143,587>172.24.1.3 80,443>172.24.1.2"  

If my fault, it could be interesting to add a section for ICMP configuration, because with a monitoring in front of a server, it's very usefull to allow it, especially without iptables skills.

Tell me if you need more info about this problem.

Great work, thanx.

**Comment by abelbeck** [comment]
I'm not sure you want ```ICMP_REDIRECT=1```

What exactly is failing, what ping from where to where ?

**Comment by StephaneMangin** [comment]
You're right, after removing redirection... It works !

Thanx and sorry to have posted an issue which is not really one...
