### ISSUE TITLE
Add LAN to DMZ forwarding policy

### ISSUE THREAD

**Issue by abelbeck** [arno-iptables-firewall/aif#30]
Currently all LAN traffic (INT_IF interfaces) is allowed to the DMZ network(s)
```
# Apply policy for LAN->DMZ (allow all)
iptables -A FORWARD -i $iif -o $dif -j ACCEPT
```
There are situations where a particular LAN should not have access to the DMZ.

One solution is with interface granularity, add a DMZ_DENY_INT_IF variable that contains INT_IF interfaces that should not be allowed to the DMZ, example pseudo-code:
```
# Apply policy for LAN->DMZ
if $iif is in $DMZ_DENY_INT_IF
iptables -A FORWARD -i $iif -o $dif -j DROP
else
iptables -A FORWARD -i $iif -o $dif -j ACCEPT
```

Another approach is general filtering granularity, add a LAN_DMZ_FORWARD_CHAIN which defaults to one rule of ACCEPT
```
# Apply policy for LAN->DMZ (default to allow)
iptables -A FORWARD -i $iif -o $dif -j LAN_DMZ_FORWARD_CHAIN
```
then add support for the following rules:
```
LAN_DMZ_HOST_DENY_TCP=""
LAN_DMZ_HOST_DENY_UDP=""
LAN_DMZ_HOST_DENY_IP=""
```
which would be applied with a new function ```setup_lan_dmz_forward_chain()``` adding defined DROP rules before the default ACCEPT in the new LAN_DMZ_FORWARD_CHAIN.

@arnova Thoughts ?

**Comment by abelbeck** [comment]
Thinking about this more, it seems to me interface granularity is appropriate, but it may be more clear to add a LAN_DMZ_ALLOW_IF variable, when unset defaults to the current "(allow all)" default.

Change
```
# Apply policy for LAN->DMZ (allow all)
iptables -A FORWARD -i $iif -o $dif -j ACCEPT
```
to
```
# Apply policy for LAN->DMZ (allow all INT_IF when LAN_DMZ_ALLOW_IF is not set)
for interface in ${LAN_DMZ_ALLOW_IF:-INT_IF}; do
  if [ "$iif" = "$interface" ]; then
    iptables -A FORWARD -i $iif -o $dif -j ACCEPT
    break
  fi
done
```
This also guarantees LAN_DMZ_ALLOW_IF interfaces are part of INT_IF.

Any LAN->DMZ traffic not part of a defined LAN_DMZ_ALLOW_IF will ultimately be logged at the end of the FORWARD chain if FORWARD_DROP_LOG=1 and DROP'ed.

**Comment by arnova** [comment]
Doesn't LAN_DMZ_HOST_OPEN/DENY give us more control, if required? That also may be more in line with what we already have. Ofc I can always be convinced otherwise ;-)

**Comment by abelbeck** [comment]
@arnova I appreciate your commit comment :-)  BTW I have the new LAN_DMZ_ALLOW_IF already in production where I needed a completely isolated guest WiFi VLAN on a setup with a pre-existing DMZ defined.  Works perfectly.  Also more robust than potentially having to add LAN_DMZ_HOST_DENY_xxx rules using IPv4/IPv6 addresses to identify the guest WiFi VLAN subnet.

That being said, even with this new LAN_DMZ_ALLOW_IF addition,  the idea of LAN_DMZ_HOST_DENY_xxx rules is not mutually exclusive, we could do both if you wanted.  Though with the new LAN_LAN_HOST_OPEN_xxx rules, using INT_IF interfaces might often be the better general solution and use the DMZ when it's default policies are appropriate.

**Comment by abelbeck** [comment]
Fixed in 2.0.1g

**Comment by 00ebenezer** [comment]
We have a need to block LAN hosts from accessing SSH (TCP 22) to any and all DMZ hosts. What is the best way to accomplish this? I tried using LAN_DMZ_HOST_DENY_TCP but it doesn't seem to work. Any assistance would be greatly appreciated.

**Comment by abelbeck** [comment]
@00ebenezer : we did not implement the `LAN_DMZ_HOST_DENY_xxx` rules.  Quote from above ...

> Though with the new LAN_LAN_HOST_OPEN_xxx rules, using INT_IF interfaces might often be the better general solution and use the DMZ when it's default policies are appropriate.

Basically, if you want to selectively filter between internal networks, it is better to use `INT_IF` interfaces, isolated by default, then use `LAN_LAN_HOST_OPEN_xxx` rules to pass what you want.

But if you have a `DMZ_IF` network, you could add a custom rule (untested) in `/etc/arno-iptables-firewall/custom-rules`:
```
custom_lan_dmz_deny_ssh()
{
  local lan IFS
  
  echo "[CUSTOM RULE] Denying LAN -> DMZ access for SSH"
  IFS=' ,'
  for lan in $INT_IF; do
    iptables -A DMZ_FORWARD_OUT_CHAIN -i $lan -p tcp --dport 22 -j DROP
  done
}
custom_lan_dmz_deny_ssh
```

**Comment by 00ebenezer** [comment]
Thank you so much, Lonnie. That worked great!

**Comment by 00ebenezer** [comment]
I would like to log the DROP attempts. Would you please be so kind as to add a log option to the above custom-rule? I would greatly appreciate it.

**Comment by abelbeck** [comment]
@00ebenezer : Sure ...
```
custom_lan_dmz_deny_ssh()
{
  local lan IFS

  echo "[CUSTOM RULE] Denying LAN -> DMZ access for SSH"
  IFS=' ,'
  for lan in $INT_IF; do
    iptables -A DMZ_FORWARD_OUT_CHAIN -i $lan -p tcp --dport 22 \
      -m limit --limit 3/m --limit-burst 1 \
      -j LOG --log-level $LOGLEVEL --log-prefix "AIF:Deny LAN->DMZ SSH: "
    iptables -A DMZ_FORWARD_OUT_CHAIN -i $lan -p tcp --dport 22 -j DROP
  done
}
custom_lan_dmz_deny_ssh
```
This rate limits the logging to 3 logs per minute (`--limit 3/m`).
