### ISSUE TITLE
Connection Tracking Helpers

### ISSUE THREAD

**Issue by abelbeck** [arno-iptables-firewall/aif#35]
As of Kernel 4.7, AIF users are seeing this message:
```
nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
```
Ref: https://askubuntu.com/questions/906197/weird-iptables-log-messages-after-upgraded-to-server-zesty-17-04

It appears by default the only ```nf_conntrack_<helper>``` AIF enables is "ftp".  "irc" is a firewall.conf option and "sip" is in an optional plugin.

An excellent reference is here:

"Secure use of iptables and connection tracking helpers"
https://home.regit.org/netfilter-en/secure-use-of-helpers/

BTW, this should not be confused with the ```nf_nat_*``` helpers, AFAIK.

I don't have any commit ideas at this point, but we need to get a handle on this.

**Comment by arnova** [comment]
Basically we should drop the old stuff and start using --ctstate. We could make it backwards compatible with try_iptables, so we first try whether --ctstate works and if not fallback to the old rules.

**Comment by abelbeck** [comment]
It appears both the kernel version and iptables version play into supporting conntrack --ctstate matching, though kernel legacy support is helped by the fact "state" is just an alias to "conntrack" at some point.

So, while we are using (currently in AIF):
```
-m state --state ESTABLISHED -j ACCEPT
```
We are actually most likely internally using (via kernel module alias):
```
-m conntrack --ctstate ESTABLISHED -j ACCEPT
```

More difficult (ugly) to handle is the CT helpers require an extra rule to work in some versions.

Possibly we should rethink if the nf_conntrack_ftp helper should be enabled by default.

**Comment by arnova** [comment]
IMO it should, I think there's still a lot of active-ftp being used out there.

**Comment by abelbeck** [comment]
Implemented in https://github.com/arno-iptables-firewall/aif/releases/tag/2.0.2-RC1 for testing.
