### ISSUE TITLE
IPv6 NAT table is not flushed

### ISSUE THREAD

**Issue by abelbeck** [arno-iptables-firewall/aif#36]
Starting with Linux kenel 3.7 ip6tables gained support for IPv6 NAT, iptables added support with v1.4.17 in 2012-Dec-25.

Regardless of the good/bad of IPv6 NAT, AIF should be flushing and deleting all ```ip6tables -t nat``` rules as we do for ```ip4tables -t nat```.

BTW, the NETMAP target is very useful for IPv6 unique local address (ULA) routing. A work in progress NPTv6 AIF plugin is here:
https://sourceforge.net/p/astlinux/code/HEAD/tree/branches/1.0/package/arnofw/net-prefix-translation/

So, what is the best way to handle this, do we test for IPv6 NAT support and if/then in various places, or simply use ```try_ip6tables``` so any errors are ignored.  These actions only occur when AIF is started/stopped/restarted.

I'm suggesting using ```try_ip6tables```, ex.
```
try_ip6tables -t nat -F
try_ip6tables -t nat -X
```

@arnova agree ?

**Comment by arnova** [comment]
yup, totally makes sense. Anything that comes from kernel by default should be flushed/zapped.
