### ISSUE TITLE
ipv6 routing not working with 2 interfaces.

### ISSUE THREAD

**Issue by nimbius** [arno-iptables-firewall/aif#44]
ip6 prefixes delegated by dhcpcd to two internal networks do not appear to function correctly.  

ETH1,ETH0 = Internal
ETH2=external.

only one interface can properly route ipv6 through the firewall.  ipv4 traffic functions as expected.

**Comment by abelbeck** [comment]
@nimbius AIF does not directly effect IPv6 routing, only filtering.

Are both eth0 and eth1 interfaces showing /64 delegations ?

Possibly you are only getting a single /64 prefix from your ISP ?

Use `ip -6 r` to show your IPv6 routing table and try to see what is going on.
