### ISSUE TITLE
Service active while process dead

### ISSUE THREAD

**Issue by NginUS** [arno-iptables-firewall/aif#46]
I installed arno-iptables-firewall & answered the questions during setup, but its status says it's dead. Is there more I need to do?

```
$ sudo service arno-iptables-firewall status
● arno-iptables-firewall.service - Arno's Iptables Firewall                                                                                            
   Loaded: loaded (/lib/systemd/system/arno-iptables-firewall.service; disabled; vendor preset: enabled)                                               
   Active: inactive (dead)
```

**Comment by arnova** [comment]
Checking the status this way doesn't work since AIF doesn't run as a daemon. You should execute "arno-iptables-firewall status" to see whether there are any firewall rules in place.

**Comment by campones** [comment]
well I did the setup script as usual  and no rules are detected, neither using the shell command, neither do they appear on webmin firewall.  Usually I d use webmin to save the rule AIF created

**Comment by arnova** [comment]
If still a problem, please use the mailinglist for further support.
