### ISSUE TITLE
configure.sh and systemd

### ISSUE THREAD

**Issue by bryce-lynch** [arno-iptables-firewall/aif#50]
Just wanted to point out that the guided configuration script fails on my system. It seems to look for /etc/init.d/arno-iptables-firewall and reports aif "is not installed on this system".

My system is an Arch Linux using systemd, so I have no init.d. To bypass the sanity_check() function I have to fake the directory like this: mkdir -p /etc/init.d/arno-iptables-firewall

**Comment by arnova** [comment]
This has been fixed in f3f2b0a35dbe1ce72d0d0d3e0d51f87391c7062a . Thanks for reporting!
