### ISSUE TITLE
AIF 2.0.3 on Red Hat EL 8 beta

### ISSUE THREAD

**Issue by eigenmachina** [arno-iptables-firewall/aif#54]
Just though I'd drop a note to say there seems to be some issues with AIF and Red Hat EL 8. For example, when an IP from the FULL_ACCESS_HOSTS list is processed the call to "get_ifs <IP address>" results in "interfaces" being set to "+". On CentOS 7 (basically Red Hat EL 7) the following rule is set:

iptables -A EXT_INPUT_CHAIN -i + -s <IP address> -d 0/0 -j ACCEPT

and "iptables -S" shows the following so that <IP address> is allowed through:

-A EXT_INPUT_CHAIN -s <IP address>/32 -j ACCEPT

In this case the version of iptables is 1.4.21.

On Red Hat EL 8 (iptables 1.8.0) the same procedure as above results in "iptables -S" showing the following:

-A EXT_INPUT_CHAIN -s <IP address>/32 -i <binary data>+ -j ACCEPT

where <binary data> is just some non-ASCII jumble which does not allow <IP address> through. This was tested using AIF 2.0.3.

It appears that AIF is relying on the fact that "-i +" used to behave as "any interface", but it seems this is no longer the case. Indeed, the documentation for iptables is ambiguous in this respect:

[!] -i, --in-interface name
    Name of an interface via which a packet was received (only
    for  packets entering the INPUT, FORWARD and PREROUTING chains).
    When the "!" argument is used before the interface name, the
    sense is inverted.  If the interface name ends in a "+", then
    any interface which begins with this name will match. If this
    option is omitted, any  interface name will match.

so it's not clear what should happen if the interface name is null (the man page hasn't changed in this regard between 1.4.21 and 1.8.0).

It's true that Red Hat EL 8 is still in beta, but this seems to be more of an issue with how iptables is now parsing the "-i" setting, and might be worth looking into.

**Comment by eigenmachina** [comment]
Sorry, github is messing around with less/greater than brackets (and I can't seem to edit my original post, this interface is truly terrible).

In any case, here is what I hope is the proper report:

Just though I'd drop a note to say there seems to be some issues with AIF and Red Hat EL 8. For 
 example, when an IP from the FULL_ACCESS_HOSTS list is processed the call to "get_ifs [IP address]" results in "interfaces" being set to "+". On CentOS 7 (basically Red Hat EL 7) the following rule is set:

iptables -A EXT_INPUT_CHAIN -i + -s [IP address] -d 0/0 -j ACCEPT

and "iptables -S" shows the following so that [IP address] is allowed through:

-A EXT_INPUT_CHAIN -s [IP address]/32 -j ACCEPT

In this case the version of iptables is 1.4.21.

On Red Hat EL 8 (iptables 1.8.0) the same procedure as above results in "iptables -S" showing the following:

-A EXT_INPUT_CHAIN -s [IP address]/32 -i [binary data]+ -j ACCEPT

where [binary data] is just some non-ASCII jumble which does not allow [IP address] through. This was tested using AIF 2.0.3.

It appears that AIF is relying on the fact that "-i +" used to behave as "any interface", but it seems this is no longer the case. Indeed, the documentation for iptables is ambiguous in this respect:

[!] -i, --in-interface name
    Name of an interface via which a packet was received (only
    for  packets entering the INPUT, FORWARD and PREROUTING chains).
    When the "!" argument is used before the interface name, the
    sense is inverted.  If the interface name ends in a "+", then
    any interface which begins with this name will match. If this
    option is omitted, any  interface name will match.

so it's not clear what should happen if the interface name is null (the man page hasn't changed in this regard between 1.4.21 and 1.8.0).

It's true that Red Hat EL 8 is still in beta, but this seems to be more of an issue with how iptables is now parsing the "-i" setting, and might be worth looking into.

**Comment by arnova** [comment]
I've reported this upstream to the netfilter/iptables team but unfortunately they still haven't responded yet. Hopefully this is fixed by them and backported by Redhat else we'll have to have a look at a workaround on our side (which is non-trivial)

**Comment by Atavic** [comment]
Seems like it is related to Red Hat [beta release](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/8.0_beta_release_notes/overview):

> The nftables framework replaces iptables in the role of the default network packet filtering facility. 

[Networking](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/8.0_beta_release_notes/new-features#networking_2)

**Comment by arnova** [comment]
I believe all outstanding issues are fixed in 2.1.0-RC1
