### ISSUE TITLE
Using local interface aliases instead of local network addresses

### ISSUE THREAD

**Issue by 00ebenezer** [arno-iptables-firewall/aif#65]
I have a multi-interface firewall that I use a .conf file to configure the rules. I'm trying to setup something like this:

Instead of using 10.10.10.0/24>192.168.1.0/27~3389

I'd like to use eth0>eth1~3389.  Is that possible? How would I go about setting this up to use interface aliases instead of network addresses?

**Comment by abelbeck** [comment]
> I'd like to use eth0>eth1~3389. Is that possible?

Not with AIF, referencing just the interfaces is not specific enough, in general.

**Comment by 00ebenezer** [comment]
Alright, thank you for your time and information.

**Comment by arnova** [comment]
@00ebenezer : Please, next time use the mailinglist for support questions. Github issues is only for reporting bugs or feature requests. Thanks!
