### ISSUE TITLE
Opening ports on specific IP

### ISSUE THREAD

**Issue by ossii79** [arno-iptables-firewall/aif#67]
Is there any config options to open for example 80,443 to the world, but only on a specific interface?
In the case where you have eth0 eth0:1 eth0:2 with 3 different IPs, I'd like only eth0:2 and its IP to be exposed to the world, not the two other IPs.

So basically have a OPEN_TCP="21,22,1919,6363,7777,19922" as usual with an addition of:
OPEN_TCP_INT=80,443-local.ip2 1200-local.ip0"

Or any other current way of doing this?

-Osi

**Comment by arnova** [comment]
Yes, you can. Try OPEN_TCP="local.ip2#80,443 local.ip0#1200". Note that this is also mentioned in the README file. Please note that Github is not for general support, the next time please use our mailinglist.
