### ISSUE TITLE
ipv6nd_sendadvertisement not permitted

### ISSUE THREAD

**Issue by nimbius** [arno-iptables-firewall/aif#69]
using dhcpcd with prefix delegation set for internal interfaces causes ipv6nd_sendadvertisement: Operation not permitted error.  

example: (enp3s0 is the public interface)

interface enp3s0
  ipv6rs                         # enable routing solicitation get the
  ia_na 0                        # request an IPv6 address           
  ia_pd 1 enp3s0/1 
  ia_pd 2 enp2s0/2 wlx9cefd5febaca/3

private interfaces enp2s0 and wlx9cefd5febaca do NOT receive a pd.

**Comment by abelbeck** [comment]
Are you certain AIF's rules is blocking the traffic ?

I personally use AIF with wide-dhcpv6 to offer PD for LAN clients.

**Comment by nimbius** [comment]
this can be disregarded.  There was a prefix change at my upstream provider.
