### ISSUE TITLE
FTP - can't retrieve directory

### ISSUE THREAD

**Issue by campones** [arno-iptables-firewall/aif#71]
Hello

setting up a new server and after I installed aif, I can't connect via ftp anymore. it says Error:	Failed to retrieve directory listing

I opened port 21 though, what is the cause of this 

thanks

**Comment by abelbeck** [comment]
Hi @campones  : AIF 2.0.2 or later should work.  There was an issue with Linux Kernel 4.7+ that we had to adjust to, fixed with PR #35 .

Older kernels should work as well.

If you have 2.0.2 or later, make sure FTP is not being blocked before your AIF firewall.

Or, don't use FTP anymore :-)

**Comment by campones** [comment]
the fix I found was to enable those ephemeral ports for passive connection in proftpd config file and then open those ports with iptables 

**# In some cases you have to specify passive ports range to by-pass
# firewall limitations. Ephemeral ports can be used for that, but
# feel free to use a more narrow range.
PassivePorts                  49152 65534
**
iptables -I INPUT -p tcp --dport 49152:65534 -j ACCEPT

**Comment by campones** [comment]
Sadly I have ubuntu 18 and I thought the package would be quite recent so I just used the package installer to have AIO..

**Comment by abelbeck** [comment]
Here is the 2.0.2 release:
https://github.com/arno-iptables-firewall/aif/releases/tag/2.0.2

@arnova knows much more than I for upgrading Debian/Ubuntu.

If you must use the proftpd `PassivePorts` range, I would suggest making it much smaller so the `iptables` rule can have a much smaller range ... possibly 49152:49199 small.

**Comment by campones** [comment]
I see, I ll do this or remove it after I setup the server, I just need ftp to transfer files at the beginning. 

thanks

**Comment by campones** [comment]
as for upgrading, I guess the best is to just apt-get remove "package" and manually install the tar file you linked to me

**Comment by abelbeck** [comment]
There is an `install.sh` script.

**Comment by arnova** [comment]
> as for upgrading, I guess the best is to just apt-get remove "package" and manually install the tar file you linked to me

Right, that's how I also update my Debian/Ubuntu/Mint systems and is the easiest way. Btw. for security reasons I recommend not working around your issue by simply adding "iptables -I INPUT -p tcp --dport 49152:65534 -j ACCEPT", which is something that reminds me too much about the crappy hack for ipchains due to it being stateless.
