### ISSUE TITLE
Error: either "to" is duplicate, or "equalize" is garbage

### ISSUE THREAD

**Issue by danielpaten** [arno-iptables-firewall/aif#76]
When the multiroute.conf is enabled, I received an error in /var/log/message.log
Error: either "to" is duplicate, or "equalize" is garbage

According : https://rocky.eld.leidenuniv.nl/pipermail/firewall/2013-July/002357.html
In 50multiroute.plugin I changed the line 
ip route add default equalize \
to
ip route add default scope global \

It appears to work perfectly, but not sure it's correct ?

Daniel

**Comment by arnova** [comment]
Strange, I'm pretty sure this used to work. But to be honest: I haven't used this plugin for a very long time, so perhaps something changed in the ip-command causing it to fail. Will look into it when I have the time. Thanks for your report.

**Comment by arnova** [comment]
Btw. : what distribution / kernel are you using? I think equalize got dropped in newer kernels, causing this issue.

**Comment by danielpaten** [comment]
Here the infos:
uname -a
Linux  4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
CentOS Linux release 8.1.1911 (Core)

**Comment by danielpaten** [comment]
Maybe it can help you:
https://build.opensuse.org/package/view_file/openSUSE:Factory:PowerPC/iproute2/iproute2.changes
See line 1014.... Dropped equalize support ...

**Comment by arnova** [comment]
Thanks a bunch for the info! Will update the plugin accordingly.
