### ISSUE TITLE
AIF blocking nimble

### ISSUE THREAD

**Issue by campones** [arno-iptables-firewall/aif#92]
Hello

I m having an issue with aif (first time) . I m setting up nimble streaming server and it just won't work despite I opened the customs port I setup for its purpose.
Any idea?

```
[tcp @ 000001f68579e0c0] Connection to tcp://example.com:1934?tcp_nodelay=0 failed: Error number -138 occurred
[rtmp @ 000001f680891980] Cannot open connection tcp://example.com:1934?tcp_nodelay=0
rtmp://xxx:xxx@example.com:1934/live/stream: Error number -138 occurred
```

I m also having this issue but I m totally not sure it s related (I tried this from the shell of the server itself precisely to avoid connecting from outside)

```
Problem accessing the DNS. (addr: no)
rtmp://xxx:xxx@example.com:1934/live/stream: Unknown error occurred
```

**Comment by arnova** [comment]
Your config/firewall logs please....

**Comment by campones** [comment]
I m sorry I forgot to apply the configuration after adding those 2 ports (https-alt and a custom rtmp port).
It's funny that restarting aif doesn't apply the new configuration but since I added those threw the webmin firewall manager, that must explain it ..
